config/routes.rb
Rxngif::Application.routes.draw do

  root :to => "Pictures#index"

  # Create
  get "/pictures/new" => "Pictures#new", :as => "new_picture"
  post "/pictures" => "Pictures#create", :as => "pictures"

  # Read
  get "/pictures" => "Pictures#index", :as => "pictures"
  get "/pictures/:id" => "Pictures#show", :as => "picture"

  # Update
  get "/pictures/:id/edit" => "Pictures#edit", :as => "edit_picture"
  put "/pictures/:id" => "Pictures#update", :as => "picture"

  # Destroy
  delete "/pictures/:id" => "Pictures#delete", :as => "picture"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :url, :caption, :favorite
  # THIS HAS NOTHING TO DO WITH ATTR_ACCESSOR
  # THIS HAS NOTHING TO DO WITH WHICH COLUMNS WE HAVE IN THE TABLE
  # THIS IS ONLY FOR WHITELISTING WHICH COLUMNS CAN BE MASS ASSIGNED

  validates_presence_of :url
  validates_uniqueness_of :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def update
    @pic = Picture.find_by_id(params[:id])

    if @pic.update_attributes(params[:picture])
      redirect_to @pic, :notice => "Picture updated successfully."
    else
      render 'edit'
    end
  end

  def create
    @pic = Picture.new(params[:picture])
    if @pic.save
      redirect_to pictures_url, :notice => "Picture created successfully."
    else
      render 'new'
    end
  end

  def edit
    @pic = Picture.find_by_id(params[:id])
  end

  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html { render 'index' }
      format.json { render :json => @pictures }
    end
  end

  def show
    @pic = Picture.find_by_id(params[:id])

    respond_to do |format|
      format.html { render 'show' }
      format.json { render :json => @pic }
    end
  end

  def new
    @pic = Picture.new
  end

  def delete
    p = Picture.find_by_id(params[:id])
    p.destroy
    redirect_to pictures_url, :notice => "Picture toasted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RXNGIF</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <header>
    <h1><%= link_to "RXNGIF", root_url, :id => "logo" %></h1>
  </header>

  <div id="notice"><%= notice %></div>

  <%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<% if @pic.errors.any? %>
  <div id="errors_collection">
    <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="picture">
  <%= form_for @pic do |f| %>
    <fieldset>
      <div>
        <%= f.label :url %>
        <%= f.text_field :url, :placeholder => "Enter the picture's source" %>
      </div>
      <div>
        <%= f.label :caption %>
        <%= f.text_field :caption, :placeholder => "Enter a caption" %>
      </div>
      <div>
        <%= f.label :favorite %>
        <%= f.check_box :favorite %>
      </div>
    </fieldset>
    <%= f.submit %>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<h2>Edit Picture #<%= @pic.id %></h2>

<nav>
  <%= link_to "Cancel", @pic %>
</nav>

<%= render 'form' %>

app/views/pictures/index.html.erb
<nav>
  <%= link_to "Add A New Picture", new_picture_url %>
</nav>

<ul id="pictures">
  <% @pictures.each do |pic| %>
    <li class="picture">
      <%= link_to image_tag(pic.url, :class => "pic #{"favorite" if pic.favorite }"), pic %>
      <p><%= pic.caption %></p>
      <nav>
        <%= link_to "Show", pic %>
        <%= link_to "Edit", edit_picture_url(pic) %>
        <%= link_to "Delete", pic, :method => "delete" %>
      </nav>
    </li>
  <% end %>
</ul>

app/views/pictures/new.html.erb
<h2>Add A New Picture</h2>

<nav>
  <%= link_to "Cancel", pictures_url %>
</nav>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h2>Showing Picture #<%= @pic.id %></h2>

<nav>
  <%= link_to "Back", pictures_url %>
  |
  <%= link_to "Edit", edit_picture_url(@pic) %>
</nav>

<div class="picture">
  <%= image_tag @pic.url, :class => "pic #{"favorite" if @pic.favorite }" %>

  <p><%= @pic.caption %></p>
  <% if @pic.favorite %>
    <p>Favorite</p>
  <% else %>
    <p>Not Favorite</p>
  <% end %>
</div>